fast_lio:
  ros__parameters:
    common.lid_topic:  "/scan"
    common.imu_topic:  "/imu/data_raw"

    common.lidar_type: 3
    common.scan_line:  18
    common.blind:      0.3
    common.det_range:  40.0

    common.max_iteration:       4
    common.filter_size_corner:  0.1
    common.filter_size_map:     0.2

    common.imu_acc_n:   0.1
    common.imu_gyr_n:   0.01
    common.imu_acc_w:   0.001
    common.imu_gyr_w:   0.0001
    common.imu_gravity: 9.80

    common.extrinsic_T: [0.0, 0.0, 0.0]
    common.extrinsic_R: [1.0, 0.0, 0.0,
                         0.0, 1.0, 0.0,
                         0.0, 0.0, 1.0]
